version: 2.0
jobs:
  test:
    docker:
      - image: jbl90/ca_project
    steps:
      - checkout:
      - run:
          name: test
          command:
            python tests.py
      - store_test_results:
          path: build/test-results

  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/app:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/app:$CIRCLE_SHA1

  deploy:
    docker:
      - image: circleci/python

    steps:
      - checkout:
      - run:
        name: Deploy Over SSH
        command: ssh $SSH_USER@$SSH_HOST



workflows:
  version: 2
  three_job_flow:
    jobs:
      - test
      - dockerize:
          requires:
            - test
      - deploy:
          requires:
            - dockerize


